language: python
python:
  - "2.7"
install:
    - npm install
script:
    - npm run test
before_deploy:
    - pip install sphinx_rtd_theme
    - pip install travis-sphinx
deploy:
    - provider: script
      script: bash .travis/gen_ghpage.sh
      on:
        branch: master