name: workflow
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  TRAVIS_COMMIT_MESSAGE: ${{github.event.commits[0].message}}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Install Node.js
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install npm packages
        run: pnpm install
      - name: Build
        run: |
          pnpm run check
          pnpm run build
      - name: Artiface Archive
        uses: actions/upload-artifact@v2
        with:
          name: Super_preloaderPlus_one_New.user.js
          path: dist/Super_preloaderPlus_one_New.user.js
          if-no-files-found: error
      - name: Test
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
        with:
          args: npm test
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
      - name: Install Node.js
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install npm packages
        run: pnpm install
      - name: Build
        run: |
          pnpm run check
          pnpm run build
      - name: Build documentation
        run: pnpm run docs:publish
      - name: Deploy to Github Pages
        if: ${{ github.event_name == 'push' && success() }}
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs/.vitepress/dist
          keep_history: true
          commit_message: ${{ format('Commit sha {0}', github.sha)}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
